version: "3"
services:
  db:
    image: postgres
  db2:
    image: mongo
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/sindicato
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db2